### PR TITLE
Cr photos add missing pokemon

### LINKED ISSUE #15: make pokemon cards for people who didn't submit cards

### PR DESCRIPTION
**Pull request by CheoR**
## Link to Ticket

make pokemon cards for people who didn't submit cards [Link](https://github.com/nss-day-cohort-46/nss-day-cohort-46.github.io/issues/15)

Closes #15 

## Description of Proposed Changes

Created pokemon cards for fun images with no pokemon card.

## Steps to Test

```sh
git fetch --all
git checkout cr-photos-addMissingPokemon
Open landing page and visit the following cards

Blu
Calvin
Phllip
Caleb 
```

## Impacted Areas in Application

List general components of the application that this PR will affect:

* Click on image to see poke card.

## Mentions @username

Tag users that need to review this code

### CODE REVIEW

**Review by calebsjames — APPROVED** [review]
I'm good with this but we should get approval from everyone who had their cards changed before merging.

**Comment by nch66862** [comment]
Calvin said it looked good to him @CheoR

**Comment by CheoR** [comment]
Phillip submitted a substitution which is on the pull request now. I'm waiting for a response from Blu and I think that should be it.

**Comment by CheoR** [comment]
Blu approves.

**Review by bpotts11 — APPROVED** [review]

**Pull request merged**
